import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css"
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <header
        className="
          flex 
          space-x-10  
          items-center 
          justify-around
          mt-8
          mb-5
        "
      >
        <h1
          className="
            text-4xl
            font-bold
            text-center
            text-gray-800
          "
        >
          <Link href="/">Image processor</Link>
        </h1>
        <nav className="
          flex 
          space-x-10  
          items-center 
          justify-around
          mt-8
          mb-5
          w-1/3
        ">
          <Link
            className="
              text-blue-600
              font-semibold
              underline 
              underline-offset-4
              hover:text-blue-800
              hover:underline-offset-8
              transition-all
              duration-300
              ease-in-out
              hover:shadow-lg
            "
            href="/about"
          >
            О программе
          </Link>
          <Link
            className="
              text-blue-600
              font-semibold
              underline 
              underline-offset-4
              hover:text-blue-800
              hover:underline-offset-8
              transition-all
              duration-300
              ease-in-out
              hover:shadow-lg
            "
            href="/history"
          >
            Обработанные
          </Link>
        </nav>
      </header>
      <main>
        {children}
      </main>
    </body>
  </html>

  );
}
