"use client";

import Script from "next/script";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css"
import Link from "next/link";

import SmartNav from "./components/SmartNav";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/SmartMenus/1.1.1/css/sm-core-css.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/SmartMenus/1.1.1/css/sm-blue/sm-blue.min.css"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header
          className="
          flex 
          space-x-10  
          items-center 
          justify-around
          mt-8
          mb-5
        "
        >
          <SmartNav></SmartNav>
        </header>
        <main>
          {/* Подключение jQuery и SmartMenus */}
          <Script src="/vendor/smartmenus/js/jquery.smartmenus.min.js" strategy="beforeInteractive" />
          <link rel="stylesheet" href="/vendor/smartmenus/css/sm-core-css.css" />
          <link rel="stylesheet" href="/vendor/smartmenus/css/sm-blue/sm-blue.css" />
          <Script src="/scripts/smartmenus-init.js" strategy="afterInteractive" />

          {children}
        </main>
      </body>
    </html >

  );
}
